### ISSUE TITLE
functionality for temperature

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#10]
[temperature]
display the outside temperature in Estes Park. the data is going to come from AccuWeather. It will be displayed using a modified widget from AccuWeather. in the simulated display, it will show blue 59°F and below, cyan 60-69°F, green 70-89°F, red 90°F and above while displaying the temperature.

**Comment by iankilgore** [comment]
functionality finished, just a few more steps, closed 20150504190712
