### ISSUE TITLE
Sleep sounds

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#2]
Need to create three sleep sounds in the format of mp3, ogg or wav. The sounds should be able to loop.
i fixed all the bugs.
--Anonymous

**Comment by iankilgore** [comment]
we are not going to have the recording looped, we are going to make it be 5 minutes due to it becoming quieter.

**Comment by iankilgore** [comment]
I have a 5 minute file and i believe it's .wav

**Comment by iankilgore** [comment]
files uploaded:
sleep_sound_1
sleep_sound_2
sleep_sound_3
