### ISSUE TITLE
Time sounds

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#20]
1. one
2. two
3. three
4. four
5. five
6. six
7. seven
8. eight
9. nine
10. ten
11. eleven
12. twelve
13. thirteen
14. fourteen
15. fifteen
16. sixteen
17. seventeen
18. eighteen
19. nineteen
20. twenty
21. thirty
22. forty
23. fifty
24. The time is
25. pm
26. am
27. oh
28. clock

**Comment by iankilgore** [comment]
this issue should have been closed at 20150504195345 due to the sounds being recorded after that
it's closed now...
