### ISSUE TITLE
You can still click on hello, moshi when sleep sound plays

### ISSUE THREAD

**Issue by iankilgore** [iankilgore/moshi#21]
On the real moshi alarm clock, it doesn't let you do that. To stop the sleep sound, just push on the display, so in the simulation, to stop the sleep sound, just click where the time is and it'll stop playing.

**Comment by iankilgore** [comment]
It has to be just in the alarm clock area though, we might be able to tell people the area by making a small table border,  or they would just figure out about where it is eventually

**Comment by LeeKilgore** [comment]
Haha, you labeled your own ticket "feature creep. "  That's really funny.

**Comment by iankilgore** [comment]
paused sleep sound when hello moshi is clicked
