### ISSUE TITLE
background rotates through a list of colors

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#4]
alternates between 6 colors:
blue(1a0aff), cyan(00ffff), green(00ff55), yellow(a8ff64), red(de0614), purple(a806de)

**Comment by iankilgore** [comment]
We need to also make sure that you can turn it off like you can on the original clock

**Comment by iankilgore** [comment]
Instead of making it the background, let's make it so that its a small portion of the page

**Comment by iankilgore** [comment]
I guess it looks cool having the whole thing lit up.  I tested it last night in the dark and I think I found the perfect hex numbers that make it reflect off the wall with an awesome effect, I think we could close this one.  Closed 20150512084553.
