### ISSUE TITLE
functionality for alarm command

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#5]
[alarm]
shows you the time the alarm is currently set to (hh:mm)in a dialog box and waits for ok to be clicked

**Comment by iankilgore** [comment]
We could also add a line like this
SetTimeOut () 4000;
So that it will be like moshi

**Comment by iankilgore** [comment]
we got the alarm function done, all we have to do is make a popup windows that is blue (1a0aff).
