### ISSUE TITLE
rearrange code

### ISSUE THREAD

**Issue by iankilgore** [iankilgore/moshi#52]

**Comment by LeeKilgore** [comment]
We'll rewrite moshi using jQuery and a moshi object.

moshi

## properties

```
time
facecolor
date
day
alarm sound
sleep sound
alarm on off
ampm
face on off
alarm time
temperature
sleep sound on off
currentCommand
```

## functions

```
getTime
setTime
displayTime
hideTime
sayTime
getFaceColor
setFaceColor
displayFaceColor
getDate
setDate
displayDate
sayDate
getDay  
setDay
displayDay
sayDay
setAlarmTime
turnAlarmOn
turnAlarmOff
getAlarmTime
checkAlarmTime
getAlarmSound
setAlarmSound
turnAlarmSoundOn
turnAlarmSoundOff
displayAlarmIcon
hideAlarmIcon
getSleepSound
setSleepSound
turnSleepSoundOn
turnSleepSoundOff
startNightLight
stopNightLight
getTemperature
setTemperature
displayTemperature
sayTemperature
hideTemperature
acceptCommand
displayDialogBox
hideDialogBox
```

**Comment by LeeKilgore** [comment]
http://thenextweb.com/insider/2015/07/27/a-simple-developer-error-is-exposing-private-information-on-thousands-of-websites/

**Comment by iankilgore** [comment]
Get time will get the current time.  Set time will set the time once the current time is loaded.  Display time will show the clock and do everything it's doing right now.  Hide time will be triggered whenever something else displays. Say time will say the the time, it goes with the time command.  Get face color will get the current color moshi is on.  Set face color will change it during another time. Display face color will make it so that it displays that desired color.  Get date will get the current date. Set date will set the date variable just like the time.  Display date will display the date. Say date will say the date just like the time.  Get day i think will get the current day of the week or month.  Set day will set the day of the week or month it got.  Display day will display it just how everything else was.  Set alarm time makes it so that you can set the alarm time.  Turn alarm on and off enables you to turn on and off the alarm.  Get alarm time will grab the alarm time.  Check alarm time makes it so that it checks the alarm for making different functions work.  Get alarm sound will look at what the alarm sound is at so that when the alarm is set, the correct alarm sound is played.  Set alarm sound will be triggered when you select an alarm sound.  Not sure what Turn alarm sound on and off do exactly.  Display alarm icon is triggered when the alarm is turned on.  hide alarm icon means when alarm is turned off.  get and set sleep sound will get and set the current sleep sound number.  Turn sleep sound on will be triggered when you click play sleep sound.  Turn sleep sound off is triggered when the sleep sound is done.  Start night light be triggered when night light is clicked.  Same with off.  Get temperature will get the temperature from the widget.  Set temperature will set the temperature variable.  Display temperature will display the temperature on moshi's display.  Say temperature will make it so that moshi will say the temperature.  Hide temperature will be triggered when the function times out.  Accept command will look at the command you chose.  Display dialog box will display the command dialog box.  Hide dialog box is triggered when you select a command.

**Comment by LeeKilgore** [comment]
moved on to moshi 2.0
