### ISSUE TITLE
make new html layout for date

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#55]
for the days of the week, the arrow icon, and the date.

**Comment by iankilgore** [comment]
![moshi-table-borders](https://cloud.githubusercontent.com/assets/11303001/9275527/df6bf9e6-425a-11e5-8c47-a045d047750b.png)

**Comment by iankilgore** [comment]
i don't know if i know what you're meaning for this issue and the other one

**Comment by iankilgore** [comment]
I think we got this done pretty much.
