### ISSUE TITLE
night light off link to be gone!

### ISSUE THREAD

**Issue by iankilgore** [iankilgore/moshi#60]
Instead of a night light off link, we would make it so that if the night light is on, select night light command again to turn it off.

**Comment by iankilgore** [comment]
YEAH!!!! I GOT THIS DONE!!!  I WAS ACTUALLY ABLE TO FIGURE OUT HOW TO DO THIS AND MANY THINGS!!  YES!!!  I CAN FINALLY CLOSE THIS ISSUE!!!  YYYEEEAHHH!!

**Comment by LeeKilgore** [comment]
Good job Ian. I'll see you in a little while.
