### ISSUE TITLE
functionality for [alarm sound] command

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#7]
[alarm sound]
it will offer three alarm sounds and will play what each one sounds like. After you type it in, it will play it once.

**Comment by iankilgore** [comment]
This will work kind of like how the sleep sound did, and when the current time reaches the set alarm time, the alarm will go off, when the alarm clock is making noise, it will be blue, when there is the silent 4 second part, it will be green.

**Comment by LeeKilgore** [comment]
For some reason the .wav files don't load correctly or play when they are called from the web page.  I used some different alarm sounds from the web and they work.  The set alarm functionality is done but the pop up window probably needs adjusting to specific colors and size and location.

**Comment by iankilgore** [comment]
If I understand right the sleep sound and alarm sounds are too big and
don't work, I have an idea, we could split it into two.

**Comment by LeeKilgore** [comment]
The problem is with the format of the .wav files.  Something isn't quite right.  I tested some large .wav files and they worked properly.  I also tested the "command please" .wav file in place of the .wav files that aren't working and it worked fine.

**Comment by iankilgore** [comment]
one more thing we need to add is that we need to make it so that the alarm only plays for one beep when the alarm links are clicked. We need to make sure that when we click on those, it's setting a variable to 1, 2, or 3. We need to do the same for the sleep sound.

**Comment by iankilgore** [comment]
We need to make it so that the alarm sound plays for only 1-2 seconds, but we will have to make the set alarm function work and make the clock play the alarm at the correct time, it will wait until the current time matches the alarm time.
