### ISSUE TITLE
functionality for [play sleep sound] command

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#8]
[play sleep sound]
it will play the sleep sound selected for 5 min.

**Comment by iankilgore** [comment]
1. Computer looks at current selected sleep sound
2. If night light is not already on it will be turned on, once the sleep sound is done it will turn off the night light.
3. Every 15 seconds or so, it will start night light over with blue like it does on the real clock.
   I'll have to look on moshi to see what it actually does and we can make it that way.
