### ISSUE TITLE
functionality for [sleep sound]

### ISSUE THREAD

**Issue by LeeKilgore** [iankilgore/moshi#9]
[sleep sound]
it will offer three sleep sounds to choose from and play what each one sounds like. After you type it in, it will play it once.

**Comment by iankilgore** [comment]
Moshi: To choose a sleep sound, say, sound 1 [sound 1 sample], sound 2 [sound 2 sample], or sound 3 [sound 3 sample]. 
That's what moshi will say and then you would say "sound 1" or "sound 2" or "sound 3" to pick the sound. We need to maybe have buttons or something to pick 1, 2, or 3.

**Comment by LeeKilgore** [comment]
The sleep sounds do not work when called from the web page.  Maybe the file size is too large.  I haven't tested to figure out why yet.  But for the functionality of the sleep sound, if you look at the code for the alarm, it should be very similar.

**Comment by iankilgore** [comment]
we need to make it so that it only plays for 1.5 seconds

**Comment by iankilgore** [comment]
When the sleep sounds only play for 1.5 seconds, we will have to get the play sleep sound function working.
